# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetDetective' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PetDetective

  target 'PetDetectiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PetDetectiveUITests' do
    # Pods for testing
  end

  pod 'NMapsMap'

end
